const ProtoBuf = require('protobufjs')
const path = require('path')
const fpath = path.join(__dirname, 'protocol.proto')
const builder = ProtoBuf.loadProtoFile(fpath)
module.exports = builder.build('srpc')
